### ISSUE TITLE
Make Reason Parser lightweight using cppo

### ISSUE THREAD

**Issue by bobzhang** [reasonml/reason#1247]
For the version compatible with BuckleScript, it would be nice to provide the highest quality parser - stable, easy to be vendored, fast, small binary size etc.
Note cppo is just dev dependency, we run the pre-processor before deploying, for other versions, it is fine to keep depending on migrate-parsetree.

Another suggestion, ocamlbuild is really not a hackable build tool, it will get more and more complex when you want more customizations, I would suggest Makefile as a better fit for the current reason dev build, since I expect if we take my suggestion above, most work is actually tweaking the build..

**Comment by jordwalke** [comment]
Thanks for the suggestion. Can you explain how cppo solves the problem of making the build process for the parser lighter weight?

You probably are aware of what OMP does, but I'll explain the motivation for anyone else who is curious:
Before ocaml migrate parsetree, we had the following dilemma: we had written our parser based on the 4.02.3 version of the AST, and then we wanted to support *using* Reason from newer versions of OCaml. We had some people who had to use 4.02.3 still (for BuckleScript), and others who wanted 4.03, and a more who wanted to test bleeding edge features with Reason 4.04. It would have been a huge hassle to support parsing and printing of these versions (and who knows what else is to come in OCaml). We didn't want Reason to be a second class citizen, always lagging behind OCaml versions while we have to go add support for the new version - and so instead we worked with @let-def to build on OCaml Migrate Parsetree, which automates support for all future versions. We can build a parser against `4.04`, and have it work with `4.02.3` *or* `4.04`. We have continuous integration tests running that ensure that we will work with all versions of OCaml >= 4.02.3 and above, and "OMP" will even give us OCaml `4.05` for free because it will perform the AST version conversion without us having to change Reason.

The best part was that it works with BuckleScript too (if not, we will fix it) because when using `-pp refmt` it produces an AST that is always compatible with the version of the compiler you're using (4.2.3 even) *not* the version of the compiler that Reason parsed into (4.04). This also gives BuckleScript the same flexibility to move to a new compiler version when it is ready and Reason support will be automatic.

Still, it seems you would really like to build a version of Reason inside of Bucklescript, and It sounds like you're having trouble building migrate parse tree in the process. What is the specific trouble? What is the specific errors you are encountering. We might be able to come up with an approach that works for your goal but without having to fork build processes. Still, we would love to improve Reason's build process to be much simpler anyways - so maybe there's some ways to simplify the primary opam build process, that makes it easier for you to vendor Reason?

> Another suggestion, ocamlbuild is really not a hackable build tool.

What we have is mostly inherited from m17n project, and we're definitely open to other suggestions for a build tool. Specifically if you have a different tool in mind besides `topkg`, please feel free to suggest them.  I'd like to avoid having multiple build processes so that means we strive for something that works everywhere. If you published bspack to opam, would that open up this opportunity? Makefiles are great and simple, but it's not clear if that will make it harder to build for windows or not (if we go with an msys2 approach, it will not make it harder, but if we go with another approach it will). I assume bspack will work on windows either way, so if you think it's worthwhile to publish bspack to opam, please let me know the tradeoffs you see.

**Comment by bobzhang** [comment]
Why I don't want to pull omp into bucklescript toolchain is the benefit does not justify its complexity for bucklescript users. Keep in mind both Reason and BuckleScript are already fairly complex, and introducing yet another layer of abstraction could work out in theory, but layers of abstractions used to introduce subtle bugs, slower build,  more maintainance cost etc. It is even more diffcult to pinpoint which part goes wrong

**Comment by jordwalke** [comment]
From the standpoint of the Reason project developers, OMP certainly seems like the only way to sustainably support multiple versions. Any other solution I can think of results in reliving the nightmare that ppx plugins had to go through to support multiple versions before OMP came along. Although, we're definitely open to other suggestions if you have them.

At the same time, I can see how the added layer of indirection doesn't help BuckleScript users that don't use Reason. Maybe there's some pretty simple things we can do to make it easy for you to build just the parser. For example, there's some places in the code like this:

```
open Migrate_parsetree
open Ast_404
module From_current = Convert(OCaml_current)(OCaml_404)
module To_current = Convert(OCaml_404)(OCaml_current)
```

Have you considered grabbing some pre-generated versions of `Migrate_parsetree`, `OCaml_404` and `OCaml_current` (where `OCaml_current` is `4.02.3`) and just vendoring them into BuckleScript? Then, when you generate a pack of reason-parser, you can blacklist the *actual* ocaml migrate parse tree perhaps. I seem to recall that the most complicated part of migrate parse tree is *generating* those conversion functions, and I'm curious if it would simplify things to do that conversion ahead of time.

Also, did you follow up on the prebuilt binaries solution? Would that work as well? We would like to get reason onto opam windows as well and that might make the prebuilt binaries path easier.

Aside from those, do you have any other specific suggestions? I'm all for simplifying the build system itself (removing topkg). We were searching for a simpler build system that would generate all the annoying boiler plate like `META` and `opam.install` file etc, but we couldn't find anything simpler than topkg.

**Comment by jordwalke** [comment]
I can try to think of more ideas for simplifying if you would be willing to post an error message that shows some of the problems that are being caused. If `cinaps` is giving you trouble, then I think something is wrong because `cinaps` should be completely gone by the time you get to the point of compiling `reason-parser` or `omp`. If you would like to try to create a bspack, have you tried doing so from within the root of the `node_modules` directory for `reason-cli`, which has all the dependencies - including `omp` which should be in its *published* form which has gotten rid of `cinaps` by that point.

**Comment by bobzhang** [comment]
I am not convinced to invest in migrate-parsetree at this time, I may revisit it half a year later.
You can still use omp for other versions as below:

```ocaml
#if OCMAL_VERSION = (4,02,3)
   (* don't use omp *)
#else 
   (* use omp *) 
#end
```

Taming complexity makes sense for large projects, suppose you have 10 ppxes going on, when something went wrong, it is difficult to know which ppx is to blame (espeically for some subtle bugs, like attributes dropped accendentially)

**Comment by bobzhang** [comment]
I do wish we keep focused at this time, do one thing well, then we get more people to work on more great stuff

**Comment by jordwalke** [comment]
> I do wish we keep focused at this time, do one thing well, then we get more people to work on more great stuff

I agree, and omp has helped us to focus on building React instead of spending time supporting all the different ocaml versions. Still, I absolutely recognize that this causes some friction in the case of BuckleScript, and I'm willing to spend some time making things simpler. Let's continue to explore the simplification options.

As it is right now - does bspack "just work" on the parser without needing to do any hacks/special cases?
If not, what error did you encounter? I can take a look and try to help resolve the error.

If bsb did just work without any hacks/special cases, would this be simple enough?

The cppo solution might work. It does introduce another Reason dependency though, so I would prefer if it was not needed and we could make bspack work without cppo. Quick question: is cppo easy to integrate with ocamlbuild/toppkg? Does it work on mly files too?

**Comment by bobzhang** [comment]
Note cppo is only a dev dependency, you run the cppo, check in the preprocessored code, then you don't need it any more

**Comment by jordwalke** [comment]
I took a closer look at the problem. cppo itself isn't too bad of a dependency to have (someone would just need to do the work to integrate it into our build). But the *use* of cppo alone wouldn't make it so that the problem is solved as simply as:

```
#if OCAML_VERSION = (4,02,3)
   (* don't use omp *)
#else 
   (* use omp *) 
#end
```

The primary challenge is the fact that the AST shape itself is different across versions. For example, 4.03 represents named arguments differently than 4.02.3, and 4.04 likely adds even more changes. We will need to keep up with every change if we have to surround each changed AST form with an if/def. I think that cppo could help but it's not enough to make it sustainable.

I wonder if something like this would work:
```
#if BYPASS_OMP
   open Migrate_parsetree_Shim_404.Ast
#else 
   open Migrate_parsetree.OCaml_404.Ast
#end
```

Where the "shim" has a hard coded bundle of the OMP just for the purpose of converting between 4.02.3 and 4.04.
That means there's only one place in the parser where you need this cppo, but more importantly, as we continue to upgrade the version of the AST that Reason parser parses into, we can automatically regenerate that shim.
Please let me know if you think this would be a satisfactory solution, and I can see how hard it would be to compute that shim.

**Comment by jordwalke** [comment]
@chenglou showed me some errors that occur when trying to use bspack. The issue is that omp uses a small ppx transform to generate the ml files that it uses and we can't  figure out how to get bspack to use ppx. (Cinaps is not a problem - it's gone by that point). It should be pretty straight forward to pregenerate the .ml files needed for bspack. You could even grab the omp that converts from 404 to 402 and perform by hand the replacements.

If this is sufficiently simple I can manually generate those files. If it's not simple enough, would you be willing to list the requirements so that I can find another option? I have a couple more ideas if this one doesn't work out.

**Comment by jordwalke** [comment]
>  I need checkout what is cinaps

Cinaps is complicated but completely gone by the time we run bspack iirc.


>  if there is no magic meta-programming

There is, admitedly, a little meta-programming, and my goal would be to try to find a way to remove that while still reaping the benefits of omp. I understand that feels like a bit of a burden on BuckleScript, so I'm willing to help out and eliminate the metaprogramming if possible. Sounds like you agree I should at least look into it. I will do so this weekend or next week!


> But if I work on reason, I would make a fine tuned version for the bucklescript version at this time 

Yes, and I investigated what that would take - cppo would work too, but it would require many places of cppo in both the parser and the printer because the actual shape of the AST changes across versions (and will continue to change). I'm not 100% opposed to it, but I'd like to save it as a last resort if none of the other approaches work.
