### ISSUE TITLE
Custom keywords

### ISSUE THREAD

**Issue by ShalokShalom** [reasonml/reason#1382]
A lot of people seem to have very difference preferences between which characters and keywords should get used for the different functionality. 

I suggest to provide a solution that enables us to decide by ourself, what works for us. 

This also provides the possibility to translate keywords into other mother languages

**Comment by SanderSpies** [comment]
The solution you are searching for is what we are using: the Menhir parser
generator. It would be unfortunate if we would try to do the same thing.
There is nothing stopping you from forking Reason and changing the syntax
as you see fit though.

Also code is meant to be read and I'm not sure that a lot of different
Reason syntaxes is going to help with that.

Regarding preferences: we want to be appealing to JS developers and that's
it for now.

On Sep 1, 2017 11:29 AM, "ShalokShalom" <notifications@github.com> wrote:

A lot of people seem to have very difference preferences between which
characters and keywords should get used for the different functionality.

I suggest to provide a solution that enables us to decide by ourself, what
works for us.

This also provides the possibility to translate keywords into other mother
languages

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/reason/issues/1382>, or mute the thread

**Comment by ShalokShalom** [comment]
I mean of course local. This parser can change anything, once released.
