### ISSUE TITLE
update to newer OCaml compilers

### ISSUE THREAD

**Issue by hannesm** [reasonml/reason#1414]
Dear reason developers,

first thank you very much for this project!  If I understand correctly, reason currently depends on / uses OCaml 4.02.3.  Is this correct?

Is there a roadmap on rebasing it onto newer OCaml compilers?  I mainly ask because the MirageOS project recently moved (in its 3.0 release) to `OCaml 4.03+`, and I'd like to know whether in the foreseeable future I'd be able to develop unikernels in both reason and OCaml.  Other reasons for newer OCaml compilers include (potentially security critical) bugfixes (such as various integer overflows in String/Array.concat etc.). 

I'm sorry if this has already been discussed elsewhere, but I couldn't find any such discussion.

Thanks again for the project, and keep up the good work!

**Comment by hcarty** [comment]
You can have OCaml up through 4.04.2, though not 4.05.0 I think. The 4.02.3 restriction comes from Bucklescript, so if you're targeting native/mirage/jsoo you don't have to worry about the 4.02.3 restriction.

**Comment by jordwalke** [comment]
@hcarty @hannesm Thanks for asking. Reason the syntax portion should work with every version of OCaml because we use OMP (an OCamlLabs project). There's one thing we need to improve, and that is breaking up Reason into smaller opam packages that don't impose additional constraints on packages. For example, right now reason provides `rtop`, a `utop` for Reason, but that ends up putting a ton of additional package manager constraints (which might be an issue but not always). If you or anyone is interested in helping us break up the project into several smaller opam projects, that would be greatly appreciated. I have a bit of experience with opam, but I'll be honest that it's pretty confusing to me.

**Comment by hcarty** [comment]
The current releases in opam are restricted to OCaml <4.05.0, even for the OMP-using versions. I'm not sure if there's a technical conflict or if it's a restriction that can be lifted.

**Comment by jordwalke** [comment]
I think we just don't have test cases for them running in Travis and we haven't tested. If we upgrade to the latest OMP as well, then there's no reason it shouldn't work. Any help is appreciated.

**Comment by hannesm** [comment]
due to lack of activity here, and my lost interest, I'm closing this issue. thanks for your work.

**Comment by anmonteiro** [comment]
For folks reading this after the fact:

- Reason supports OCaml 5.1 (RC1 just released yesterday)
- It targets the ppxlib AST, which should support all the modern compilers
