### ISSUE TITLE
JSX children `...<div foo bar baz/>` could format better

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1594]
Repro:

```reason
<Wrapper>
  ...<div
       foo=fooooooooooooooo
       bar=barrrrrrrrrrrr
       baz=bazzzzzzzzzzzz
       qux=quxxxxxxxxxxxx
       quux=quuxxxxxxxxxxxx
     />
</Wrapper>;
```

Maybe it should be formatted as:

```reason
<Wrapper>
  ...<div
     foo=fooooooooooooooo
     bar=barrrrrrrrrrrr
     baz=bazzzzzzzzzzzz
     qux=quxxxxxxxxxxxx
     quux=quuxxxxxxxxxxxx
   />
</Wrapper>;
```

Should it? If not, I'll close this. Though this might be a better example:

```reason
<Foo>
  ...(
       ReasonReact.stringToElement(
         <Barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
           baaaaaaaaaaaaaazzzzzzzzzzzz
           quuuuuuuuuuuuuuxxxxxxxxxxxxxxx
         />
       )
     )
</Foo>;
```

Maybe we should only do it for parens? Also, there are some other cases where parens and the expression should be hugged together. @rickyvetter you had an example?

**Comment by IwanKaramazow** [comment]
I agree with "hugging" `(` with `ReasonReact.stringToElement`.
But
```reason
<Wrapper>
  ...<div
     foo=fooooooooooooooo
     bar=barrrrrrrrrrrr
     baz=bazzzzzzzzzzzz
     qux=quxxxxxxxxxxxx
     quux=quuxxxxxxxxxxxx
   />
</Wrapper>;
```
just looks very weird.

**Comment by chenglou** [comment]
So you prefer the current form?

**Comment by rickyvetter** [comment]
I'd like to avoid all extra indentation if possible. It makes the code less uniform and the styling more contextually aware. I think this is a negative because it adds noise to code reviews when context changes and unrelated whitespace also changes. For that reason, I prefer the minimal indentation versions that @chenglou recommended (A,B). I agree that it doesn't look as good in some cases, but I think it still reads just as well for clarity and is more consistent.

The other one that bothers me is tangentially related to JSX in that it happens with `make` functions a lot. I added in C the current formatting and D my desired formatting. This aligns with Prettier and the Hack printer and follows the same rule across all of these examples of ending a wrapping at the same indentation level as the line where it was opened.

Figures:
A. 👍
```js
<Wrapper>
  ...<div
    foo=fooooooooooooooo
    bar=barrrrrrrrrrrr
    baz=bazzzzzzzzzzzz
    qux=quxxxxxxxxxxxx
    quux=quuxxxxxxxxxxxx
  />
</Wrapper>;
```
B. 👍
```js
<Foo>
  ...(ReasonReact.stringToElement(
    <Barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
      baaaaaaaaaaaaaazzzzzzzzzzzz
      quuuuuuuuuuuuuuxxxxxxxxxxxxxxx
    />
  ))
</Foo>
```
C. 👎
```js
let make =
    (
      ~firstProp: option(thing),
      ~secondProp: option(thing),
      ~thirdProp: thing,
      ~fourthProp: thing,
      state
    ) => foo;
```
D. 👍
```js
let make = (
  ~firstProp: option(thing),
  ~secondProp: option(thing),
  ~thirdProp: thing,
  ~fourthProp: thing,
  state
) => foo;
```

**Comment by IwanKaramazow** [comment]
I'll see what I can do, I can follow the reasoning behind the change.

**Comment by chenglou** [comment]
This might be slightly controversial, so let's focus just on parens hugging and D for now. Those are fairly tame.

**Comment by IwanKaramazow** [comment]
So for `B` parends hugging without the indentation?
