### ISSUE TITLE
New attribute syntax

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#1951]
One common feedback folks have expressed is that the attribute syntax looks weird. I thought it was similar enough to JS/Python/etc that folks wouldn't mind, but I guess that's not the case. Here's a proposal:

```reason
/* attached to bar */
@foo bar

/* with payload */
@foo(10) bar

/* multiple args */
@foo(10, 20) bar

/* tuple */
@foo((10, 20)) bar

/* extension point */
%%foo;
%%foo(bar);
let a = %foo;
let b = %foo(bar);
```

**Comment by IwanKaramazow** [comment]
Houston, we have a problem
```
/* foo attribute with payload 10 */
@foo(10) bar
/* foo attribute on expression 10 */
@foo (10)
```
Menhir can't decide whether to shift to the payload or reduce the attribute here. I'm afraid that this isn't `LR(1) ` terrain.

**Comment by jaredly** [comment]
can't we make it whitespace-significant?

**Comment by IwanKaramazow** [comment]
We can, trying it out.

**Comment by IwanKaramazow** [comment]
Good news, made a small prototype and the brace-less attributes is going to fly due to a small massage in the lexing.

Bad news, I'm not sure if the braceless extension has a LR(1) grammar:
```reason
%foo -1;  (extension_sugar on the structure_item containing the expression (-1) )
%foo open Foo;

VS

%foo - 1; (extension_expression (minus infixop) exp_constant)
```
When the parser sees `%foo`, is it an `extension_sugar` or an `extension` (expression)?

**Comment by jaredly** [comment]
ooh let's not do the braceless there -- it should be `%foo(-1)`. `%foo -1` should be a syntax error

**Comment by IwanKaramazow** [comment]
The problem is backwards compatibility. We currently have the following syntax extension sugar
```
%lwt
let x = 1;

%foo
-1;
```
Both forms should co-exist.
I'm taking another look at the parser, maybe I've overlooked something.

**Comment by jordwalke** [comment]
I'm not sure what "multiple args" would mean. Right now, attributes accept sequences:

```
[@foo let x = 0; x + x];
```

There isn't a notion of multiple args.

**Comment by IwanKaramazow** [comment]
I interpreted "multiple args" as a list of `structure_items`.
```
@foo(
  let x = 1,
  let y = 2,
  x + y
)
```
^^  this might look very weird

**Comment by jordwalke** [comment]
I think it looks a bit weird since it would be the only place that structure items use commas.
I'm still a little hung up on the white space significant meaning because if we were to ever add white space significant meaning in other parts of the grammar, the meaning in those other places might be very different than the meaning implied here. For example, we might one day allow supplying a *single* argument without parens if that single argument is a list etc. So `someFunc [1, 2]`. But we might want to keep the syntax for dereferencing arrays by index `arr[i]`, and we might choose to have a space represent "I'm applying a function" which is the exact opposite of what a space would mean in the case of ppx attributes here.

**Comment by chenglou** [comment]
Can we just do `@foo({let x = 1; let y = 2; x + y})`?
Also, I'm not against paren-less single arg application, but I do believe that folks would want this attribute change more so than the current syntax + potential backlash (not to mention the uncertainly) of paren-less space application

**Comment by iddan** [comment]
Is this still relevant?
