### ISSUE TITLE
Build instructions for (inexperienced) contributors

### ISSUE THREAD

**Issue by hoichi** [reasonml/reason#2506]
Do you think maybe we need some Getting started instructions for potential contributors with little experience in opam, Dune, Azure, etc.

Personally, I’m looking at the repo and I have some questions like:
- do you build via `make` or via Azure CI
- are there steps you need to run before you run make?
- how do you start with Azure? Create your personal account and upload the repo?

Of course, maybe any build-related contributions simply needs more experienced contributors. Maybe babysitting inexperienced devs is simply not worth it. What do you think?

**Comment by thangngoc89** [comment]
git clone
npm install -g esy 
esy

**Comment by hoichi** [comment]
Thanks a lot!

But should this information be more accessible? Then again, it’s available in `src/README.md`, so maybe I just didn’t look well enough.

**Comment by jordwalke** [comment]
Yeah, I think that our current README is weird because it includes the information that the *fewest* number of people would find relevant. It discusses the API version of Reason (calling it as an API) which very few people actually ever need to use.

Let's use this as an opportunity to rethink the most important things that belong on the README.


1. Link to "how to develop doc" - as well as a brief summary (@thangngoc89's instructions).
2. Information on how to consume it.

**Comment by hoichi** [comment]
> Information on how to consume it.

Exactly. I have to admit that even after running esy I still have a hard time figuring out:
1. What have I just built? And how do I consume it? (E.g., I presume that the script builds `reason` & `rtop`, but how do I use what I’ve built? Should I alter my path so as not to point to `rtop` installed by bs-platform?
2. Where are those docs?

Again, I don’t know how ignorant you want your contributors, but if you want some noob feedback, there you are :)

**Comment by anmonteiro** [comment]
please reopen if still having issues setting up the repository
