### ISSUE TITLE
Very confusing quick start Error: theme basic-reason not found

### ISSUE THREAD

**Issue by AkechiShiro** [reasonml/reason#2633]
I have tried the instruction from the quick-start and ran into this error :

```
npm install -g bs-platform
bsb -init my-first-app -theme basic-reason # --> Fails here
cd my-first-app
npm run start
```

I don't think I'm supposed to get this error, previous to that `bsb` has been installed correctly using `npm` I can provide further details if needed to diagnose what's going on here.

Here is the ouput during the installation of bsb :

```log
/usr/bin/bsb -> /usr/lib/node_modules/bs-platform/bsb
/usr/bin/bsc -> /usr/lib/node_modules/bs-platform/bsc
/usr/bin/bsrefmt -> /usr/lib/node_modules/bs-platform/bsrefmt
/usr/bin/bstracing -> /usr/lib/node_modules/bs-platform/lib/bstracing

> bs-platform@8.3.1 postinstall /usr/lib/node_modules/bs-platform
> node scripts/install.js

ninja binary is already cached and installed:  /usr/lib/node_modules/bs-platform/linux/ninja.exe
checkoutput: BuckleScript 8.3.1 ( Using OCaml:4.06.1+BS )
 ocaml version 4.06.1+BS
Prebuilt compiler works good
+ bs-platform@8.3.1
added 1 package from 1 contributor in 8.46s
```

```
bsb -init my-first-app -theme basic-reason
Making directory my-first-app
Available themes: 
basic
generator
minimal
node
react-hooks
react-starter
tea
Error: theme basic-reason not found
```

**Comment by mblarsen** [comment]
Getting that too. Very anti-climatic.

**Comment by AkechiShiro** [comment]
Found any workaround or fix @mblarsen ?

**Comment by gaku-sei** [comment]
It seems that the theme has indeed been dropped https://github.com/rescript-lang/rescript-compiler/pull/4640

It really makes me feel that ReasonML and BuckleScript will not work together for a long time, it's really concerning...

**Comment by davesnx** [comment]
The only workaround is not installing the latest bs-platform (@8.2.0) and use the "basic-reason".

**Comment by AkechiShiro** [comment]
There is no other possibility than just not installing the latest `bs-platform` at the moment? @davesnx

Is there any way that the change on [rescript-lang/rescript-compiler#4640](https://github.com/rescript-lang/rescript-compiler/pull/4640) would get reversed ?

I just don't understand what is the motivation behind the removal of this theme, like it's being used by devs and I don't think it's breaking anything in their codebase hence why remove it ? I'm clueless to this. 

But in the end I'm really just a beginner here so I could be wrong about all the above.

**Comment by gaku-sei** [comment]
>I just don't understand what is the motivation behind the removal of this theme, like it's being used by devs and I don't think it's breaking anything in their codebase hence why remove it ? I'm clueless to this.

I'm just like you, totally puzzled by the whole ReScript rebranding 😕 

It _seems_ that the ReScript team is trying to remove all tracks of "ReasonML" from the doc and the tooling to make it less confusing for the newcomers. Ironically, it's even more confusing, especially since many existing libraries and docs all point to ReasonML, and that ReasonML as a brand, is still way stronger than ReScript...

To make it clear, if someone wants to use BuckleScript, they have to use ReScript or get a degraded experience if they use ReasonML/OCaml (no themes, no updates (the OCaml version used by the compiler is still 4.06 when the lastest version of the official compiler is already 4.11, no docs, etc...). For the native developments though, [Dune](https://dune.readthedocs.io/en/stable/overview.html) is a very nice tool and it supports ReasonML out of the box 😄 

(Funnily enough I created an issue earlier: https://github.com/facebook/reason/issues/2634 to get some clarification from the ReasonML team regarding the support of the language for the web as it seems ReasonML might be used mostly with the native OCaml compiler from now on).

**Comment by tmattio** [comment]
Hey @AkechiShiro!

Not sure the template is what you're looking for, but [Spin](https://github.com/tmattio/spin) has a template for ReScript: https://github.com/tmattio/spin-rescript

It supports both Reason and ReScript syntaxes. 

I'm happy to work on other ReScript templates if this one does not quite suit your needs. Hope it helps 🙂

**Comment by bobzhang** [comment]
hi @AkechiShiro , this is an unexpected breakage
Fixed in https://github.com/rescript-lang/rescript-compiler/pull/4808
I did not watch this repo, if you have any issues, feel free to report in rescript-compiler repo.

**Comment by ryyppy** [comment]
The whole Installation page needs to be rewritten. Reason advertises itself as a natively compiled language, but refers to `BuckleScript` (wrong name), and still contains a ReScript quickstart guide.

If you check out the [ReScript Installation](https://rescript-lang.org/docs/manual/latest/installation) section, you will see that we changed our getting started workflows.

**Comment by AkechiShiro** [comment]
Thanks for the cleaner explanation.

**Comment by ryyppy** [comment]
We removed the installation instructions on the ReasonML docs and forward users to the ReScript docs.

(See latest [PR](https://github.com/reasonml/reasonml.github.io/pull/719))
