### ISSUE TITLE
Alternative syntax for method calls.

### ISSUE THREAD

**Issue by charlesetc** [reasonml/reason#523]
It would be fantastic to be able to do 

```
foo.bar 1 2
```

instead of

```
foo#bar 1 2
```

Primarily, it would make the language more approachable for people coming from javascript, python, etc.

**Comment by jordwalke** [comment]
That would be nice. This is possible if record syntax takes a different form. Since records and objects are fundamentally incompatible, there must be a parsing time distinction.

One other compromise would be to have method call syntax appear as:
```rust
let result = myObject.myMethod:: x y z;
```

Another approach is to have objects take the record syntax, and have records take a different syntax. This is quite easy to achieve, but objects are not as fast as records, so it may not be worth changing the syntax so that objects have the "nicer" syntax.

**Comment by Charlesetc** [comment]
That makes sense - I definitely agree having dot syntax for records is a must.

    foo.bar::.baz::

is a bit awkward still. Thanks for the reasoning!

**Comment by spion** [comment]
Is there an issue to track "ideas for method call syntax"? I was going to ask whether double-dot could potentially be used

`myObject..myMethod`

If there isn't, maybe we could reopen and change the title of this one?

**Comment by jordwalke** [comment]
Sounds good, @spion. I'll reopen.

**Comment by kennetpostigo** [comment]
The PR for the implementation of of object method call syntax seems like it did not move forward. Would this be okay to close?

**Comment by anmonteiro** [comment]
no plans for this anymore
