### ISSUE TITLE
[atom-reason] Suggest to build the artifacts

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#769]
It'd be great if atom can somehow detect that the build artifacts are not up to date for merlin's analysis. In the future if people do build watch we'll need this less; still nice to have though.

**Comment by vramana** [comment]
We should be able to introspect what merlin is configured to right from atom and list of all the files it is watching.

**Comment by chenglou** [comment]
More info for those lacking context: merlin picks up artifacts and analyses them to provide help. This means the artifacts (by extension, the analysis) are always one step behind the user writing code. Usually this isn't a problem, unless we're creating new functions or files, in which case Merlin erroneously say such function/file doesn't exist.

**Comment by hcarty** [comment]
On the plus side, merlin does track new/updated definitions in the current file without an intermediate build step.  Unfortunately it can't pick up inter-file updates in its current state without rebuilding the affected file(s).

I think jenga may have some support for watching project directories for updates.

**Comment by jordwalke** [comment]
Does `Jenga` have a mode where you can tell it exactly which files to consider as "dirty"? If so, if we detect a `rebel` user, we could have all the IDE plugins tell `rebel` that a specific file has changed whenever we save. That might be faster than a general watcher. We could also do a little bit better by only telling `rebel` about a dirty file when the editor switches *away* from that buffer, so that we don't trigger rebuilds every time we hit save inside a single buffer (since Merlin does a fine job already of updating within one file). The delay to get the up-to-date artifacts will likely not be noticeable for small projects as `rebel` on `Jenga` would build those instantly. For larger projects where the delay to update artifacts will be noticeable due to deferring until buffer-switch time .. well, those projects are exactly the ones you don't want to be continuously kicking off rebuilds for when you save within your editor anyways, so deferring rebuild until buffer switch likely presents a worthwhile tradeoff!
