### ISSUE TITLE
[atom-reason] Debugger

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason#779]
That interfaces with ocamldebug. I want mah step back button!

**Comment by jordwalke** [comment]
To make it really work well we need rebel or some system that can generate a module map that tells us where each unique Module compilation artifact is located, and where its Original source file is located. Otherwise no one will use it.

**Comment by SanderSpies** [comment]
@jordwalke can you elaborate a bit more? (Not that familiar with Rebel or OCamldebug) I'm interested in getting something going. 

Btw. I think ocamldebug won't work on Windows.

**Comment by jordwalke** [comment]
I'm curious where you heard that it won't work on windows. 

 For more background, the OCaml debugger requires as input a bunch of information that describes where various modules source files reside on disk. So rebel could be our way to automatically generate that list conveniently. We also need that list for all our dependencies too if we want to step through them which is why it's good to have rebel build as much as possible.

**Comment by jordwalke** [comment]
Found the bit about Windows.
http://caml.inria.fr/pub/docs/manual-ocaml/debugger.html

Maybe one reason to favor Cygwin. Maybe we can get Cygwin to be an NPM dependency!

**Comment by OvermindDL1** [comment]
For note, the ocaml debugger has worked fine for me on Windows, but I do use the cygwin variant.

Honestly I'd say just include the compiled ocaml binaries and all as an NPM package that is depended on for Windows platforms.  That is one of the only reliable methods on Windows considering, well, its Windows...

**Comment by jordwalke** [comment]
That would also require distributing the cygwin dll's right? Might there be a way to get this to work with Msys (mingw) which doesn't require also distributing the dll?

**Comment by OvermindDL1** [comment]
Nope, the build from within cygwin produces statically linked binaries, thus it only depends on KERNEL32.DLL and MSVCRT.DLL, both of which come with Windows as they are part of Windows.  :-)

Bucklescript compiles the same way, fully standalone (and without even needing cygwin if you already have the ocaml binaries and libraries somewhere).  :-)

Take a look at how Bucklescript changed its compiling recently.  As it is just a plugin for the compiler it can use a pre-existing compiler, which makes it pretty trivial to install on Windows as the OCaml cygwin installer sets up standalone binaries as well.

**Comment by kayceesrk** [comment]
This OCaml PR is relevant to the discussion: https://github.com/ocaml/ocaml/pull/574. While this is still WIP, with native debugging and reversible execution through `rr` is better than ocamldebug in the long term.

**Comment by jordwalke** [comment]
Would you suggest that if we're going to spend time on it, we may as well target the future?
What would become of `ocamldebug`? Also, will Mark's work be compatible with multicore/effects?

Also, how would one debug bytecode produced by `ocamlc`?

**Comment by kayceesrk** [comment]
Making baseline `ocamldebug` work with Reason might not take much time. But getting it to work seamlessly on windows might take a bit of a work. It seems worthwhile to help upstream Mark's patches to get robust debugging support.

Mark's work should be fairly easily extended to support multicore/effects. However, the story is not that clear for `ocamldebug` under multicore; the mechanism it uses for reversible debugging is incompatible with multicore. That said, `ocamldebug` can be made to work under single core execution with effects, which is what I would expect to become of `ocamldebug`.

**Comment by jordwalke** [comment]
> Making baseline ocamldebug work with Reason might not take much time. But getting it to work seamlessly on windows might take a bit of a work.

I would be incredibly surprised if `Reason` made `ocamldebug` or any debugger more difficult since it merely produces a perfectly compatible binary serialization of the AST as if it were parsed that way. There was an issue with `ocamlcp` not working but that's only because it eats up the `-pp` to add its own profiling transformation - but we can just make a custom `ocamlcp` pretty easily that first runs it through Reason, and then adds the same profiling annotations needed.

Regarding `ocamldebug` with effects running on a single core: Would it appear as if we're running multiple domains, but those would be faked out to a single core? That would work pretty well from a developer experience. When step debugging, I don't as much care about *actual* parallelism (as you said - it's a performance hack 😄  ).

Will Mark upstreaming his debugging refactor make it more difficult for you to land multicore/effects?

**Comment by kayceesrk** [comment]
> Regarding ocamldebug with effects running on a single core: Would it appear as if we're running multiple domains, but those would be faked out to a single core?

True except for cases where bugs crop up due to multicore execution. I would assume those to be minority of bugs. 

> Will Mark upstreaming his debugging refactor make it more difficult for you to land multicore/effects?

debugging refactor should be mostly independent of multicore/effects. The overlap should be very minimal.

**Comment by jordwalke** [comment]
Sounds great. I'm very excited about both.
