### ISSUE TITLE
refmt incorrect for `let _ = foo`

### ISSUE THREAD

**Issue by jberdine** [reasonml/reason#843]
```
$ echo "let _ = foo" | refmt -parse ml -print re -use-stdin true -is-interface-pp false
foo;
```
The expected result is:
```
let _ = foo;
```
This matters since the expected form can be used to silence warning 32 while the current output does not.

**Comment by jordwalke** [comment]
But doesn't it treat them the same? Are they both not representing the same thing?

**Comment by hcarty** [comment]
The execute the same by default but their intent is different. The `_` is explicitly saying "I don't care about the result of this evaluation" while the `;` says "this really should return unit."

The difference is more pronounced if strict sequences are enabled since that enforces a unit return type in the `;` case.

**Comment by jordwalke** [comment]
At the top level too?

**Comment by hcarty** [comment]
For `1;` no error, `1;2` error.  So it works in OCaml but only if there's only one top level expression.

**Comment by jberdine** [comment]
Another angle on this: I hit it trying ppx_compare, which generates functions such as `compare_t` and adds `let _ = compare_t` so that warning 32 does not fire if the generated code is not used.  The result of refmt, removing the `let _`, disables this and results in warning 32 firing anyhow.

**Comment by jordwalke** [comment]
Ah, I realize this problem was only when formatting *from* ml. In that case, I wondered why `ppx_compare` would even effect this since ppx operates on the raw tree. It must be because Cristiano upgraded Infer to 4.03 and is using a more hacky approach to reformatting, but now with Fred's 4.03/4.04+ support, you shouldn't hit it anymore I believe.

**Comment by jaredly** [comment]
this still exists...

**Comment by anmonteiro** [comment]
@jaredly I can't repro the original report:

```
$ echo "let _ = foo" | refmt --parse ml
let _ = foo;
```

Did I misunderstand?
